config/routes.rb
Rails.application.routes.draw do
  resources :users
  resources :sessions
  resources :password_resets

  get 'products/:category_id/index' => 'products#index', as: :product_all
  get 'products/:category_id/new' => 'products#new', as: :new_product
  post 'products' => 'products#create', as: :products

  get 'bidding/:product_id/new' => 'biddings#new', as: :new_bidding
  post 'bidding/create' => 'biddings#create', as: :biddings

  get 'my_activity' => 'my_activities#index', as: :my_activity
  get 'check_biddings' => 'my_activities#check_biddings', as: :check_biddings

   root 'home#index'

  get 'static/index' => 'statics#index'
  get 'static/seller' => 'statics#seller'
  get 'static/products' => 'statics#products'
  get 'static/bidding' => 'statics#bidding'
  get 'static/my_activity' => 'statics#my_activity'
  get 'static/my_profile' => 'statics#my_profile'

end

app/models/bidding.rb
class Bidding < ActiveRecord::Base

  #validations
  validates :bidder_name,
            :price,
            :price_type,
            :quantity,
            :quantity_type,
            :phone,
            :email,
            :address,
            :presence => true

  # Association
  belongs_to :user
  belongs_to :product
  belongs_to :district
end

app/models/category.rb
class Category < ActiveRecord::Base
  validates :name, presence: true
  # Assosciation
  has_many :sub_categories
end

app/models/district.rb
class District < ActiveRecord::Base
  validates :name, presence: true
  # Association
  belongs_to :state
  has_many :products
end

app/models/product.rb
class Product < ActiveRecord::Base
  mount_uploader :images

  validates :images, presence: true
  validates :sub_category_id, presence: true
  validates :phone, presence: true
  validates :address, presence: true
  validates :price, presence: true
  validates :quantity, presence: true
  validates :state_id, presence: true
  validates :district_id, presence: true
  validates :close_date, presence: true
  validates :seller_name, presence: true
  validates :email, presence: true

  # Assosciation
  belongs_to :sub_category
  belongs_to :user
  belongs_to :district
  has_many :biddings
end

app/models/state.rb
class State < ActiveRecord::Base
  validates :name, presence: true
  #Association
  has_many :districts
end

app/models/sub_category.rb
class SubCategory < ActiveRecord::Base
  validates :name, presence: true
  # Association
  belongs_to :category
  has_many :products
end

app/models/user.rb
class User < ActiveRecord::Base
	has_secure_password

  validates :name, presence: true
  validates :email, presence: true
  validates :password, presence: true, on: :create
  validates :password_confirmation, presence: true, on: :create
  # validates :phone, presence: true

  # Assosiation
  has_many :products
  has_many :biddings

	def send_password_reset
		generate_token(:password_reset_token)
		self.password_reset_sent_at = Time.zone.now
		save!
		UserMailer.password_reset(self).deliver
	end

	 def generate_token(column)
    begin
      self[column] = SecureRandom.urlsafe_base64
    end while User.exists?(column => self[column])
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  helper_method :current_user

  def authenticate_user
    if current_user.blank?
      redirect_to root_path
    end
  end


  private

  def current_user
  	@current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

end

app/controllers/biddings_controller.rb
class BiddingsController < ApplicationController
  before_action :authenticate_user, :only => [:new, :create]


  def new
    @bidding = Bidding.new
    @districts = District.all
    @states = State.all
    @product = Product.find(params["product_id"])
  end

  def create
    @bidding = Bidding.new(bidding_params)
    @bidding.user_id = current_user.id
    @bidding.product_id = params['bidding']['product_id']
    if @bidding.save
      redirect_to root_path
    else
      render 'new'
    end
  end

  private

  def bidding_params
    params.require(:bidding).permit(:bidder_name, :price, :price_type, :quantity, :quantity_type, :phone, :email, :address, :district_id, :state_id, :product_id)
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @user = User.new
    @categories = Category.all
  end
end

app/controllers/my_activities_controller.rb
class MyActivitiesController < ApplicationController
  def index
    @selling_products = current_user.products
    @bidding_products = current_user.biddings
  end

  def check_biddings
    @biddings = []
    current_user.products.each do |product|
      product.biddings.each do |bidding|
        @biddings << bidding
      end
    end
    @biddings
  end
end

app/controllers/password_resets_controller.rb
class PasswordResetsController < ApplicationController
	def create
		user = User.find_by_email(params[:email])
		user.send_password_reset if user
		redirect_to root_url, :notice => "Email sent with password reset instructions."
	end

	def edit
		@user = User.find_by_password_reset_token!(params[:id])
	end

	def update
		@user = User.find_by_password_reset_token!(params[:id])
		if @user.password_reset_sent_at < 2.hours.ago
			redirect_to new_password_reset_path, :alert => "Password &crarr; 
			reset has expired."
		elsif @user.update_attributes(params[:user])
			redirect_to root_url, :notice => "Password has been reset."
		else
			render :edit
		end
	end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :authenticate_user, :only => [:new, :create]

  def index
    @products = Product.where('category_id = ?', params[:category_id])
  end

  def new
    if current_user.blank?
      flash[:error] = "Please Sign In/Sign Up to Sell Your Product"
      redirect_to root_path
    else
      @sub_categories = SubCategory.where(:category_id => params[:category_id])
      @product = Product.new
    end
  end

  def create
    @product = Product.new(products_params)
    @product.user_id = current_user.id
    @product.category_id = params['product']['category_id']
    if @product.save
      redirect_to root_path
    else
      render 'new'
    end
  end

  private

  def products_params
    params.require(:product).permit(
      :seller_name,
      :email,
      :images,
      :category_id,
      :sub_category_id,
      :phone,
      :address,
      :price,
      :quantity,
      :quantity_type,
      :price_type,
      :state_id,
      :district_id,
      :close_date,
      :other_details
      )
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
	def create
		user = User.find_by_email(params[:email])
		if user && user.authenticate(params[:password])
			session[:user_id] = user.id
			redirect_to root_url, notice: "Logged in!"
		else
			render 'new'
			flash.now.alert = "Email or password is invalid."
		end
	end

	def destroy
		session[:user_id] = nil
		redirect_to root_url, notice: "Logged out!"
	end
end

app/controllers/statics_controller.rb
class StaticsController < ActionController::Base
  layout "static"
  
  def index
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      redirect_to root_url, notice: "Thank you for signing up!"
    else
      render "new"
    end
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    @user.update_attributes(user_params)
    if @user.save
      redirect_to root_url,
      flash[:notice] =>  "User details updated successfully"
    else
      render 'edit'
    end
  end


  private

  def user_params
    params.require(:user).permit(:name,:email,:password,:password_confirmation,:phone)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/biddings/new.html.erb
<div class="container content-area-height">
  <div class="product-page-title">Bid Your Price</div>
  <br><br>
  <div class="row">
    <div class="col-sm-5">
      <form class="form-horizontal">
        <div >
          <%= image_tag(@product.images, :alt => "rss feed", :class => "bid-upload-img") %>
        </div>
        <div class="bid-details">Product Details</div>
        <div class="form-group">
          <label class="col-sm-4 control-label">Quantity</label>
          <div class="col-sm-8">
            <p class="form-control-static"><%= @product.quantity %><span> <%= @product.quantity_type %></span></p>
          </div>
        </div>
        <div class="form-group">
          <label class="col-sm-4 control-label">Price</label>
          <div class="col-sm-8">
            <p class="form-control-static"><%= @product.price %> <span> <%= @product.price_type %></span></p>
          </div>
        </div>
        <div class="form-group">
          <label class="col-sm-4 control-label">Name</label>
          <div class="col-sm-8">
            <p class="form-control-static"><%= @product.seller_name %></p>
          </div>
        </div>
        <div class="form-group">
          <label class="col-sm-4 control-label">Phone</label>
          <div class="col-sm-8">
            <p class="form-control-static"><%= @product.phone %></p>
          </div>
        </div>
      </form>
    </div>
    <div class="col-sm-2"></div>
    <div class="col-sm-5">
     <div class="bid-details">Bidding Details</div>
     <%= form_for @bidding, :html => {id: "bidding_form", :class => "form-horizontal" } do |f| %>
     <div class="form-group">
      <label for="subCtaegory" class="col-sm-4 control-label">Name</label>
      <div class="col-sm-8">
        <%= f.text_field :bidder_name, :class => "form-control", :id => "Name", :placeholder => "Name" %>
      </div>
    </div>
    <div class="form-group">
      <label for="E-mail" class="col-sm-4 control-label">E-mail</label>
      <div class="col-sm-8">
        <%= f.text_field :email, :class => "form-control", :id => "E-mail", :placeholder => "Email" %>
      </div>
    </div>
    <div class="form-group">
      <label for="phoneNumber" class="col-sm-4 control-label">Phone Number</label>
      <div class="col-sm-8">
        <%= f.text_field :phone, :class => "form-control", :id => "phoneNumber", :placeholder => "Phone" %>
      </div>
    </div>
    <div class="form-group">
      <label for="Price" class="col-sm-4 control-label">Price</label>
      <div class="col-sm-5">
        <%= f.text_field :price, :class => "form-control", :id => "Price", :placeholder => "Price" %>
      </div>
      <div class="col-sm-3">
       <%= f.select :price_type, options_for_select(ConfigCenter::Measurement::Type), {}, { id: 'districts_select', :class => "form-control" } %>
     </div>
   </div>
   <div class="form-group">
    <label for="Quantity" class="col-sm-4 control-label">Quantity</label>
    <div class="col-sm-5">
      <%= f.text_field :quantity, :class => "form-control", :id => "Quantity", :placeholder => "Quantity" %>
    </div>
    <div class="col-sm-3">
     <%= f.select :quantity_type, options_for_select(ConfigCenter::Measurement::Type), {}, { id: 'districts_select', :class => "form-control" } %>
   </div>
 </div>
 <div class="form-group">
   <label for="Address" class="col-sm-4 control-label">Address</label>
   <div class="col-sm-8">
    <%= f.text_field :address, :class => "form-control", :id => "InputBidderaddress", :placeholder => "Address" %>
  </div>
</div>
<div class="form-group">
  <label for="Address" class="col-sm-4 control-label">District</label>
  <div class="col-sm-8">
   <%= f.select :district_id, options_for_select(@districts.collect { |district|
    [district.name.titleize, district.id] }, 0), {}, { id: 'districts_select', :class => "form-control" } %>
  </div>
</div>
<div class="form-group">
 <label for="Address" class="col-sm-4 control-label">State</label>
 <div class="col-sm-8">
   <%= f.select :state_id, options_for_select(@states.collect { |state|
    [state.name.titleize, state.id] }, 0), {}, { id: 'states_select', :class => "form-control" } %>
  </div>
</div>
<!-- </form> -->
</div>
</div>
<div class="text-right">
  <%= f.hidden_field :product_id, type: "hidden", value: params['product_id'] %>
  <%= f.submit "Submit", :class => "btn btn-lg btn-primary" %>
</div>
<% end %>

</div>
<script>
  $(function() {
    $("#datepicker").datepicker();
  });
  bidding_form();
</script>

app/views/home/index.html.erb
<div class="banner" style="">
    <div class="text">Farm Hand</div>
    <p class="small-text">Platform for farmers and buyers</p>
</div>
<div class="container content-area-height">
  <!-- <div class="home-heading text-center"><span>FARM</span> - HAND</div> -->
  <div class="row">
    <% @categories.each do |category|%>
    <div class="col-sm-3">
      <div class="thumbnail">
       <img class="image-height" src="/assets/<%= category.image_name %>" alt="image">
       <div class="caption home-category">
         <h3><%= link_to category.name, product_all_path(category.id) %></h3>
       </div>
     </div>
   </div>
   <% end%>
 </div>
</div>

app/views/layouts/_flash_message.html.erb
<%
if request.xhr?
  flash_message = flash.now[:success] || flash.now[:notice] || flash.now[:alert] || flash.now[:error]
  style_classes = ""
else
  style_classes = ""
  flash_message = flash[:success] || flash[:notice] || flash[:alert] || flash[:error]
end
cls_name = "alert-info"
cls_name = 'alert-success' if flash.now[:success] || flash[:success]
cls_name = 'alert-warning' if flash.now[:alert] || flash[:alert]
cls_name = 'alert-danger' if flash.now[:error] || flash[:error]

flash_message = flash_message.strip if flash_message

%>
<% unless flash_message.blank? %>
<div id = "flash">
  <div class="<%= style_classes %> alert <%= cls_name %> fade in mb-10" data-alert="alert">
    <a class="close" data-dismiss='alert' href="#">×</a>
    <p><%= flash_message %></p>
  </div>
</div>
<% end %>

app/views/layouts/_footer.html.erb
<footer class="footer">
  <div class="container">
    <ul>
      <li><a href="#">About Us</a></li>
      <li><a href="#">Contact Us</a></li>
    </ul>
  </div>
</footer>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-default navbar-fixed-top">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="<%= root_path %>">
        <img src="/assets/farmhandlogo.png" class="logo" alt="images">
      </a>
    </div>
    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav navbar-right">
        <% if current_user.present? %>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"><%= current_user.name %> <span class="caret"></span></a>
            <ul class="dropdown-menu">
              <li><%= link_to "My Profile", edit_user_path(current_user) %></li>
              <li><%= link_to "My Activity", my_activity_path %></li>
              <li role="separator" class="divider"></li>
              <li><%= link_to "Log Out", session_path("current"), method: "delete" %></li>
            </ul>
          </li>
        <% else %>
          <li><%= link_to "Sign Up", new_user_path, remote: true %></li>
          <li><%= link_to "Log In", new_session_path, remote: true %></li>
        <% end %>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>FarmHand</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <meta charset="utf-8">
  <meta content="IE=edge" http-equiv="X-UA-Compatible">
  <meta content="width=device-width,initial-scale=1" name="viewport">
</head>
<body>
  <%= render :partial => "/layouts/header"%>
  <%= render '/layouts/flash_message' %>
  <%= yield %>
  <%= render :partial => "/layouts/footer" %>
  <%= render :partial => 'overlays/modal' %>
  <%#= render :partial => 'overlays/sign_up' %>

</body>
</html>

app/views/layouts/static.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>FarmHand</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/my_activities/_bidding_details.html.erb
<table style="width:100%">
  <tr>
    <th>Name</td>
    <th>Price</th> 
    <th>qty</th>
    <th>phone</th>
  </tr>
  <% @biddings.each do |bidding| %>
  <tr>
    <td><%= bidding.bidder_name %></td>
    <td><%= bidding.price %>/<%= bidding.price_type %></td> 
    <td><%= bidding.quantity %> <%= bidding.quantity_type %> </td>
    <td><%= bidding.phone %></td>
  </tr>
  <% end %>
</table>

app/views/my_activities/check_biddings.js.erb
heading = "Bidder Details";
bodyContent = "<%= escape_javascript(render(:partial=>'bidding_details')) %>";
showModal(heading, bodyContent);

app/views/my_activities/index.html.erb
 <div class="container content-area-height">
  <div class="product-page-title">My Activities</div>
  <br><br>
  <div class="bid-details my-act">Selling Details</div>
  <div class="row">
  <% @selling_products.each do |selling_product| %>
   <div class="col-sm-3">
    <div class="thumbnail">
     <!-- <img alt="image" src="/assets/veg.jpeg" class="image-height"> -->
     <%= image_tag(selling_product.images, :alt => "rss feed", :class =>"image-height" ) %>
     <div class="caption ">
       <div class="row">
         <div class="col-sm-5">
           <label>Name</label>
         </div>
         <div class="col-sm-7">
           <div><%= selling_product.sub_category.name %></div>
         </div>
       </div>
       <div class="row">
         <div class="col-sm-5">
           <label>Quantity</label>
         </div>
         <div class="col-sm-7">
           <div><%= selling_product.quantity %> <%= selling_product.quantity_type %></div>
         </div>
       </div>
       <div class="row">
         <div class="col-sm-5">
           <label>Min.Price</label>
         </div>
         <div class="col-sm-7">
           <div><%= selling_product.price %> / <%= selling_product.price_type %></div>
         </div>
       </div>
       <div class="row">
         <div class="col-sm-5">
           <label>Close Date</label>
         </div>
         <div class="col-sm-7">
           <div><%= selling_product.close_date %></div>
         </div>
       </div>
     </div>
   <div class="text-right">
      <%= link_to "check bidders", check_biddings_path, :class => "btn btn-danger", remote: true %>
     </div>
   </div>
 </div>
 <% end %>
</div>
<div class="bid-details my-act">Bidding Details</div>
<div class="row">
<% @bidding_products.each do |bidding_product| %>
   <div class="col-sm-3">
    <div class="thumbnail">
     <!-- <img alt="image" src="/assets/veg.jpeg" class="image-height"> -->
     <%= image_tag(bidding_product.product.images, :alt => "rss feed", :class =>"image-height" ) %>
     <div class="caption ">
       <div class="row">
         <div class="col-sm-5">
           <label>Name</label>
         </div>
         <div class="col-sm-7">
           <div><%= bidding_product.product.sub_category.name %></div>
         </div>
       </div>
       <div class="row">
         <div class="col-sm-5">
           <label>Quantity</label>
         </div>
         <div class="col-sm-7">
           <div><%= bidding_product.quantity %> <%= bidding_product.quantity_type %></div>
         </div>
       </div>
       <div class="row">
         <div class="col-sm-5">
           <label>Min.Price</label>
         </div>
         <div class="col-sm-7">
           <div><%= bidding_product.price %> / <%= bidding_product.price_type %></div>
         </div>
       </div>
       <div class="row">
         <div class="col-sm-5">
           <label>Close Date</label>
         </div>
         <div class="col-sm-7">
           <div><%= bidding_product.product.close_date %></div>
         </div>
       </div>
     </div>
   </div>
 </div>
 <% end %>
</div>
</div>

app/views/overlays/_modal.html.erb
<div class="modal fade" id="Modal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title" id="myModalLabel"></h4>
      </div>
      <div class="modal-body">
      </div>
    </div>
  </div>
</div>

app/views/password_resets/edit.htm.erb
<h1>Reset Password</h1>

<%= form_for @user, :url => password_reset_path(params[:id]) do |f| %>
  <% if @user.errors.any? %>
    <div class="error_messages">
      <h2>Form is invalid</h2>
      <ul>
        <% for message in @user.errors.full_messages %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div class="field">
    <%= f.label :password %>
    <%= f.password_field :password %>
  </div>
  <div class="field">
    <%= f.label :password_confirmation %>
    <%= f.password_field :password_confirmation %>
  </div>
  <div class="actions"><%= f.submit "Update Password" %></div>
<% end %>

app/views/password_resets/new.html.erb
<h1>Reset Password</h1>

<%= form_tag password_resets_path, :method => :post do %>
  <div class="field">
    <%= label_tag :email %>
    <%= text_field_tag :email, params[:email] %>
  </div>
  <div class="actions"><%= submit_tag "Reset Password" %></div>
<% end %>

app/views/products/index.html.erb
  <div class="container content-area-height">
    <div class="row">
      <div class="col-sm-3">
        <div class="product-page-title">Products List</div>
      </div>
      <div class="col-sm-3 text-right">
      <%= link_to "Click Here to Sell Your Product", new_product_path(:category_id => params[:category_id]), :class=>"btn btn-primary" %>
     </div>
     <div class="col-sm-6">
      <ul class="text-right">
        <li class="disp-inline">
          <select class="form-control">
            <option>Choose Place</option>
            <option>Mysore</option>
            <option>Mandya</option>
            <option>Hasana</option>
            <option>Kodagu</option>
            <option>Davanagere</option>
            <option>Hubbali</option>
            <option>Coming Soon</option>
          </select>
        </li>
        &nbsp;&nbsp;
        <li class="disp-inline">
         <select class="form-control">
          <option>Choose Product</option>
          <option>Product 1</option>
          <option>Product 2</option>
          <option>Product 3</option>
          <option>Product 4</option>
          <option>Product 5</option>
          <option>Coming Soon</option>
        </select>
      </li>
    </ul>
  </div>
</div>
<br><br>
<div class="product-overflow">
<% if @products.present? %>
<% @products.each do |product| %>
<div class="">
  <div class="col-sm-3">
    <div class="thumbnail">
      <%= image_tag(product.images, :alt => "rss feed") %>
     <div class="caption ">
       <div class="row">
         <div class="col-sm-5">
           <label>Name</label>
         </div>
         <div class="col-sm-7">
           <div><%= product.seller_name %></div>
         </div>
       </div>
       <div class="row">
         <div class="col-sm-5">
           <label>Quantity</label>
         </div>
         <div class="col-sm-7">
           <div><%= product.quantity %> <%= product.quantity_type %></div>
         </div>
       </div>
       <div class="row">
         <div class="col-sm-5">
           <label>Min Price</label>
         </div>
         <div class="col-sm-7">
           <div><%= product.price %> / <%= product.price_type %> </div>
         </div>
       </div>
       <div class="row">
         <div class="col-sm-5">
           <label>Close Date</label>
         </div>
         <div class="col-sm-7">
           <div><%= product.close_date %></div>
         </div>
       </div>
     </div>
     <div class="text-right">
      <%= link_to "Quote Your Price", new_bidding_path(product.id), :class => "btn btn-danger" unless product.user_id == current_user.id %>
     </div>
   </div>
 </div>
</div>
<% end %>
<% else %>
<p>No result found</p>
<% end %>

</div>

app/views/users/_form.html.erb
<%= form_for @user, html: {id: "sign_up_form"} do |f| %>

<div class="form-group">
  <label for="InputUsername">Name</label>
  <%= f.text_field :name, :class => "form-control", :id => "InputUsername", :placeholder => "Name" %>
</div>
<div class="form-group">
  <label for="InputEmail1">Email address</label>
  <%= f.text_field :email, :class => "form-control", :id => "InputEmail1", :placeholder => "Email" %>
</div>
<div class="form-group">
  <label for="InputPassword1">Password</label>
  <%= f.password_field :password, :class => "form-control", :id => "InputPassword1", :placeholder => "Password" %>
</div>
<div class="form-group">
  <label for="conInputPassword1">Coinfirm Password</label>
  <%= f.password_field :password_confirmation, :class => "form-control", :id => "conInputPassword1", :placeholder => "Password Confirmation" %>
</div>
<div class="modal-footer">
  <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
  <%= f.submit "Sign Up", :class => "btn btn-primary" %>
</div>
<% end %>
<script type="text/javascript">
  sign_up_form();
</script>

app/views/users/_update_form.html.erb
<div class="container content-area-height">
  <div class="product-page-title">My Profile</div>
  <br><br>
  <div class="row">
    <div class="col-sm-3">
    </div>
    <div class="col-sm-6">

      <%= form_for @user do |f| %>
        <div class="form-group">
          <label for="InputUsername">Name</label>
          <%= f.text_field :name, :class => "form-control", :id => "InputUsername", :placeholder => "Name" %>
        </div>
        <div class="form-group">
          <label for="InputEmail1">Email address</label>
          <%= f.text_field :email, :class => "form-control", :id => "InputEmail1", :placeholder => "Email" %>
        </div>
        <div class="form-group">
          <label for="InputPassword1">Password</label>
          <%= f.password_field :password, :class => "form-control", :id => "InputPassword1", :placeholder => "Password" %>
        </div>
        <div class="form-group">
          <label for="conInputPassword1">Coinfirm Password</label>
          <%= f.password_field :password_confirmation, :class => "form-control", :id => "conInputPassword1", :placeholder => "Password Confirmation" %>
        </div>
        <div class="modal-footer">
          <%= f.submit "Update", :class => "btn btn-primary" %>
        </div>
      <% end %>
    </div>
    <div class="col-sm-3"></div>
  </div>
</div>

app/views/users/edit.html.erb
<h1>User Details</h1>
<%= render "update_form" %>

app/views/users/new.html.erb
<h1>Sign Up</h1>
<%= render "form" %>

app/views/users/new.js.erb
heading = "Register Here";
bodyContent = "<%= escape_javascript(render(:partial=>'form')) %>";
showModal(heading, bodyContent);